version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy-scripts
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 1000
  AfterInstall:
    - location: after-install.sh
      timeout: 1000
  ApplicationStart:
    - location: boot.sh
      timeout: 1000
